# hey can you accept it as i want this for my hacktober fest t-shirt .PLEASE!!!!
environment:
  matrix:
  - TOXENV: "py37"
  - TOXENV: "py38"

install:
  - C:\Python35\python -m pip install tox

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - C:\Python35\python -m tox
